name: Cleanup

on:
  workflow_dispatch:

jobs:
  destroy_workspace:
    runs-on: ubuntu-latest
    name: Destroy terraform S3 workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform destroy
        uses: dflook/terraform-destroy@v1
#         with:
#          path: my-terraform-config
#          workspace: ${{ github.head_ref }}
  #---Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
