name: Explorer Lunched S3 bucket

on:
  #push: 
   # branches: master
  workflow_dispatch:

jobs:
  checkout_and_explore:
    runs-on: ubuntu-latest
    name: Check out
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List текущий репозиторий files и мы можем совершать над ними действия
        run: ls -la  
        
      - name: Проверяет/Запрашивает AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1         
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region:  "us-east-1"
     
      - name: List s3-website-html Bucket before
        run: aws s3 ls s3://s3-website-html
        
      - name: скопируем ка из контейнера в s3 bucket, а!
        run: cp templates s3://s3-website-html
        
      - name: List s3-website-html Bucket after
        run: aws s3 ls s3://s3-website-html
      


