name: Loading S3 bucket

on:
  #push: 
   # branches: master
  workflow_dispatch:

jobs:
#  checkout_and_explore:
#    runs-on: ubuntu-latest
#    name: Заходим и осматриваемся
#    steps:     
#      - name: Checkout Репозиторий
#        uses: actions/checkout@v2
#      - name: Запрашивает AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1         
#        with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}   
      
#      - name: List текущий репозиторий files и мы можем совершать над ними действия
#        run: ls -la  
#      - name: Заглянем в папку контейнера репозитория
#        run:  ls templates
#      - name: Запрашиваем полный путь
#        run:  pwd
#      - name: List s3-website-html Bucket что я положил туда вручную!?
#        run: aws s3 ls s3://s3-website-html
      
      
  Remove_data:
    runs-on: ubuntu-latest
 #   needs: checkout_and_explore
    name: Загрузка S3 bucket
    steps:        
      - name: Checkout Репозиторий
        uses: actions/checkout@v2
      - name: Запрашивает AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1         
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
         
        
      - name: load содержимое Prefix контейнера в s3 bucket
        run: aws s3 cp /home/runner/work/static_files/static_files/templates/ s3://s3-website-html/ --recursive
      - name: List s3-website-html Bucket after
        run: aws s3 ls s3://s3-website-html
        
#      - name: download во временный контейнер
#        run: aws s3 cp s3://s3-website-html/3Capture.JPG /home/runner/work/static_files/static_files/
#      - name: List текущий репозиторий files и мы можем совершать над ними действия
#        run: ls -la  
      


